mod grant_resource_permission;
pub use grant_resource_permission::UserGrantResourcePermissionResponse;

mod revoke_resource_permission;
pub use revoke_resource_permission::UserRevokeResourcePermissionResponse;
